// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQnWhL-RHDrXNXDpQgLbsQ1FCexOWc4Yc',
    appId: '1:291347469469:web:52077d0360b5df30647074',
    messagingSenderId: '291347469469',
    projectId: 'sat-hack',
    authDomain: 'sat-hack.firebaseapp.com',
    storageBucket: 'sat-hack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKYHOpBK_s81voQ7yS3fCCu31iXBNumPE',
    appId: '1:291347469469:android:5c9470c2363060df647074',
    messagingSenderId: '291347469469',
    projectId: 'sat-hack',
    storageBucket: 'sat-hack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0GdPmlYeYVCFpoRttaBauBwZgHTxo2lU',
    appId: '1:291347469469:ios:435eb8efe44ad415647074',
    messagingSenderId: '291347469469',
    projectId: 'sat-hack',
    storageBucket: 'sat-hack.appspot.com',
    iosClientId: '291347469469-37nvtt3q9c2d51iap1vpc4kqbiqhhags.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoryNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0GdPmlYeYVCFpoRttaBauBwZgHTxo2lU',
    appId: '1:291347469469:ios:435eb8efe44ad415647074',
    messagingSenderId: '291347469469',
    projectId: 'sat-hack',
    storageBucket: 'sat-hack.appspot.com',
    iosClientId: '291347469469-37nvtt3q9c2d51iap1vpc4kqbiqhhags.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoryNotes',
  );
}
